/**
 * Deploy CLI — SSH/SCP operations.
 *
 * Manages SSH configuration (key files, config generation, jump host proxy)
 * and provides high-level functions for remote command execution and file upload.
 *
 * All SSH operations use temporary config/key files that are cleaned up after use.
 * The SSH config file supports jump host proxying for environments behind bastion hosts.
 *
 * Uses only Node.js built-in modules + lib/process.ts (zero runtime dependencies).
 *
 * @module lib/ssh
 */

import { writeFileSync, unlinkSync, mkdirSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';

import type { SSHConfig, SSHOptions } from '../types.ts';
import { spawn } from './process.ts';

// ── SSH Config File Generation ──────────────────────────

/**
 * Create SSH config and key files from environment variables.
 *
 * Generates:
 * 1. A private key file (0600 permissions) from the SSH_PRIVATE_KEY content
 * 2. An SSH config file with strict host key checking disabled and optional jump host
 *
 * The generated files are placed in a temporary directory and should be
 * cleaned up with `cleanupSSH()` after all operations complete.
 *
 * @param options - SSH connection options (key content, jump host)
 * @returns Paths to the generated SSH config and key files
 * @throws Error if no private key is provided
 *
 * @example
 * ```ts
 * const sshConfig = setupSSH({
 *   privateKey: process.env.SSH_PRIVATE_KEY,
 *   jumpHost: process.env.JUMP_HOST,
 * });
 * try {
 *   await sshExec(sshConfig, 'deploy@10.0.0.3', 'remote-ops.sh health-check');
 * } finally {
 *   cleanupSSH(sshConfig);
 * }
 * ```
 */
export function setupSSH(options: SSHOptions): SSHConfig {
  if (!options.privateKey) {
    throw new Error('SSH private key is required. Set SSH_PRIVATE_KEY environment variable.');
  }

  // Create a unique temp directory for this session's SSH files
  const sshDir = join(tmpdir(), `deploy-cli-ssh-${Date.now()}`);
  mkdirSync(sshDir, { recursive: true });

  const keyPath = join(sshDir, 'deploy_key');
  const configPath = join(sshDir, 'ssh_config');

  // Write the private key with strict permissions (0600 = owner read/write only)
  // SSH refuses keys with loose permissions
  writeFileSync(keyPath, options.privateKey + '\n', { mode: 0o600 });

  // Build SSH config content
  // StrictHostKeyChecking=no is required for CI — servers may be new or rebuilt
  // UserKnownHostsFile=/dev/null prevents accumulating host keys in CI
  const configLines = [
    'Host *',
    `  IdentityFile ${keyPath}`,
    '  StrictHostKeyChecking no',
    '  UserKnownHostsFile /dev/null',
    '  LogLevel ERROR',
    '  ServerAliveInterval 30',
    '  ServerAliveCountMax 3',
    '  ConnectTimeout 10',
  ];

  // Add jump host proxy if configured
  // This allows reaching servers behind a bastion host via ProxyJump
  if (options.jumpHost) {
    configLines.push(`  ProxyJump ${options.jumpHost}`);
  }

  writeFileSync(configPath, configLines.join('\n') + '\n', { mode: 0o600 });

  return { configPath, keyPath };
}

// ── Remote Command Execution ────────────────────────────

/**
 * Execute a command on a remote server via SSH.
 *
 * Uses the SSH config file generated by `setupSSH()` for key and proxy settings.
 * Returns the captured stdout, stderr, and exit code of the remote command.
 *
 * @param config - SSH config from setupSSH()
 * @param host - SSH connection string (e.g., "deploy@10.0.0.3")
 * @param command - Remote command to execute
 * @param options - Optional timeout and pipe settings
 * @returns Captured stdout, stderr, and exit code
 *
 * @example
 * ```ts
 * const result = await sshExec(config, 'deploy@10.0.0.3', 'remote-ops.sh health-check');
 * if (result.exitCode !== 0) {
 *   console.error('Remote command failed:', result.stderr);
 * }
 * ```
 */
export async function sshExec(
  config: SSHConfig,
  host: string,
  command: string,
  options?: { timeout?: number; pipe?: boolean },
): Promise<{ stdout: string; stderr: string; exitCode: number | null }> {
  const args = [
    '-F', config.configPath,
    '-o', 'BatchMode=yes',
    host,
    command,
  ];

  return spawn('ssh', args, {
    timeout: options?.timeout,
    pipe: options?.pipe,
  });
}

// ── File Upload ─────────────────────────────────────────

/**
 * Copy files to a remote server via SCP.
 *
 * Supports single files, multiple files, and recursive directory uploads.
 * Uses the SSH config file generated by `setupSSH()` for key and proxy settings.
 *
 * @param config - SSH config from setupSSH()
 * @param host - SSH connection string (e.g., "deploy@10.0.0.3")
 * @param localPaths - Local file path(s) to upload
 * @param remotePath - Remote destination path
 * @param options - Optional recursive flag for directory uploads
 * @throws Error if SCP exits with non-zero code
 *
 * @example
 * ```ts
 * // Upload a single file
 * await scpUpload(config, 'deploy@10.0.0.3', 'scripts/remote-ops.sh', '/opt/app/scripts/');
 *
 * // Upload a directory recursively
 * await scpUpload(config, 'deploy@10.0.0.3', 'nginx/', '/opt/app/nginx/', { recursive: true });
 * ```
 */
export async function scpUpload(
  config: SSHConfig,
  host: string,
  localPaths: string | string[],
  remotePath: string,
  options?: { recursive?: boolean },
): Promise<void> {
  const paths = Array.isArray(localPaths) ? localPaths : [localPaths];

  const args = [
    '-F', config.configPath,
    '-o', 'BatchMode=yes',
  ];

  // Add recursive flag for directory uploads
  if (options?.recursive) {
    args.push('-r');
  }

  // Add all local paths, then the remote destination
  args.push(...paths);
  args.push(`${host}:${remotePath}`);

  const result = await spawn('scp', args);

  if (result.exitCode !== 0) {
    throw new Error(`SCP upload failed (exit ${result.exitCode}): ${result.stderr.trim()}`);
  }
}

// ── Cleanup ─────────────────────────────────────────────

/**
 * Remove temporary SSH config and key files.
 *
 * Should be called in a finally block after all SSH operations complete
 * to prevent leaking sensitive key material on disk.
 *
 * @param config - SSH config from setupSSH()
 */
export function cleanupSSH(config: SSHConfig): void {
  // Remove files silently — ignore errors if they don't exist
  try { unlinkSync(config.configPath); } catch { /* already cleaned up */ }
  if (config.keyPath) {
    try { unlinkSync(config.keyPath); } catch { /* already cleaned up */ }
  }

  // Try to remove the temp directory (will fail silently if not empty)
  try {
    const dir = join(config.configPath, '..');
    unlinkSync(dir);
  } catch {
    // Directory may not be empty or may already be removed — that's fine
  }
}
